### ISSUE TITLE
Support Spigot server in addition to Bukkit.

### ISSUE THREAD

**Issue by ryanneve** [richardbenson/YAMS#184]
I think adding this option should be pretty simple as Spigot and Bukkit are so closely related.

https://www.spigotmc.org

> Spigot is an implementation and continuation of the Bukkit API which has been the leading API for Minecraft servers since 2010. Fortunately for you, this also means most plugins originally developed for CraftBukkit are reverse-compatible with Spigot!

**Comment by ryanneve** [comment]
Duplicate of
https://github.com/richardbenson/YAMS/issues/165

**Comment by oldmud0** [comment]
I'm sorry, but it appears YAMS is no longer maintained. It really does ache me that many of the numerous ones out there really do suck, but YAMS needs quite a lot of work to get back with the times. 

This was built back for Minecraft Beta, and the next thing on the todo list was Bukkit, and here we are at 1.10 full release with Bukkit killed due to the takedown request, and really Spigot (originally the underdog of Minecraft servers) being the only alternative to a stock server.

I myself have lost interest in Minecraft. It's filled with minigame servers that, despite having been repeatedly been told to stop pushing a pay-to-win model, do it anyway, and practically buy their way to cram the top of the server lists with their name (\*cough cough\* Hypixel, Mineplex et al). Not to mention the 68% of servers in the normal distribution that are small and growing but end up bloating themselves with huge (and obviously protected) towns "made by the admins" (stereotypically speaking, many of which have an obsession with certain things), and then start resorting to asking for "donations" to give you plots of land and cosmetics and a rank higher than "Builder" ("Builder+", "Builder Pro", "Benefactor", etc.). Don't forget the lackluster amount of changes that have been made to Minecraft in the past year or so, most of which are just cosmetic changes instead of adding new game mechanics. 

The game is finished. The climax was reached when Notch sold out (some even argue way before that, when Notch quit developing Minecraft), and since then it's become a huge drama, and the demographics of the game have plummeted from adults to tweens.

That is my rant. Thank you for reading.

**Comment by ryanneve** [comment]
While I appreciate your concerns, my interest is solely in providing a safe fun digital playground for my kids and their friends. This game's best years may be behind it, but I think it will be around for a long time.

While YAMS hasn't been updated in awhile (and there's a long pending push request), I find it still works for me and I don't know of any alternative. Certainly It would be nice if it handled spigot a little easier. I don't think it's too much to ask someone to install GIT. I was already using SourceTree which has it built in. It would also be nice to have tools for managing bukkit/spigot plug-ins.

While my limited coding talents don't encompass anything like this (threads? GUI?) I've forked it, and will take a look if I have the time.

**Comment by oldmud0** [comment]
All right. I'll put this in my to-do list and I'll see if I have time to help you out.
